development:
    access_key_id: AKIAIWWQF5REKTC4ZYGQ
    secret_access_key: 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
    bucket: floor_sys

test:
    access_key_id: AKIAIWWQF5REKTC4ZYGQ
    secret_access_key: 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
    bucket: floor_sys

production:
    access_key_id: AKIAIWWQF5REKTC4ZYGQ
    secret_access_key: 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
    bucket: floor_sys