development: &development
      bucket: floor_sys
      access_key_id: AKIAIWWQF5REKTC4ZYGQ
      secret_access_key: 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
staging:
      <<: *development
      bucket: floor_sys

production:
      <<: *development
      bucket: floor_sys
      
      




    

 

